name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: bash build.sh

      - name: Build Clash
        uses: docker/build-push-action@v4
        with:
          context: clash
          push: true
          tags: closehandle/clash:latest

      - name: Build Clash (macvlan)
        uses: docker/build-push-action@v4
        with:
          context: clash-macvlan
          push: true
          tags: closehandle/clash:macvlan
